- mode: sync_by_title_date
  source: 
    service: evernote
    shared_url: "https://www.evernote.com/pub/zomux/anotemydiary" 

  target:
    service: wordpress
    xmlrpc_url: "http://xxx.wordpressblog.com/xmlrpc.php"
    username: "username"
    password: "password"
    title: "{title}"
    content: "{content}"
    categories: "dairy"
