- mode: forward_by_title
  source: 
    service: evernote
    shared_url: "https://www.evernote.com/pub/zomux/anotemydiary" 

  target:
    service: wordpress
    xmlrpc_url: "http://rafa.blog.cd/xmlrpc.php"
    username: "rafa"
    password: "zxczxc"
    title: "{title}"
    content: "{content}"
    categories: "dairy"

- mode: forward_by_title
  source: 
    service: evernote
    shared_url: "https://www.evernote.com/pub/zomux/anotemyidea" 

  target:
    service: wordpress
    xmlrpc_url: "http://rafa.blog.cd/xmlrpc.php"
    username: "rafa"
    password: "zxczxc"
    title: "{title}"
    content: "{content}"
    categories: "idea"

- mode: forward_by_title
  source: 
    service: evernote
    shared_url: "https://www.evernote.com/pub/zomux/anotestudy" 

  target:
    service: wordpress
    xmlrpc_url: "http://rafa.blog.cd/xmlrpc.php"
    username: "rafa"
    password: "zxczxc"
    title: "{title}"
    content: "{content}"
    categories: "Study"

- mode: forward_by_title
  source: 
    service: evernote
    shared_url: "https://www.evernote.com/pub/zomux/anotework" 

  target:
    service: wordpress
    xmlrpc_url: "http://rafa.blog.cd/xmlrpc.php"
    username: "rafa"
    password: "zxczxc"
    title: "{title}"
    content: "{content}"
    categories: "General Work"

- mode: forward_by_title
  source: 
    service: evernote
    shared_url: "https://www.evernote.com/pub/zomux/anotesmt" 

  target:
    service: wordpress
    xmlrpc_url: "http://rafa.blog.cd/xmlrpc.php"
    username: "rafa"
    password: "zxczxc"
    title: "{title}"
    content: "{content}"
    categories: "NLP"
