- mode: forward_by_title
  source: 
    service: evernote
    shared_url: "https://www.evernote.com/pub/user/notebook" 

  target:
    service: wordpress
    xmlrpc_url: "http://yourwordpressblog.com/xmlrpc.php"
    username: "yourname"
    password: "xxxxxxxx"
    title: "{title}"
    content: "{content}"
    categories: "dairy"